### PR TITLE
add Flatten option

### LINKED ISSUE #11: chunks are nested following the magic comment
We rely on a flat build folder, currently the plugin includes folder separators which causes the written chunks to be nested.
if OK, I would like to make a PR to replace or escape the `/` for chunks to remain flat

### PR DESCRIPTION
**Pull request by salzhrani**
closes #11

### CODE REVIEW

**Comment by faceyspacey** [comment]
the chunk name option on lines 186 and 194 needs to match or they wont generate chunk names that match.

aslo we need docs in the readme for this.

make sure u test it out in your app as well.

**Comment by salzhrani** [comment]
kinda stuck... any pointers appreciated.

**Comment by faceyspacey** [comment]
I'm not on my computer but if the trim name function handles both u may be able to do it all in one place there

**Comment by Aetherall** [comment]
Hi ! Is this PR ready for testing ?

**Comment by faceyspacey** [comment]
It's not. It needs to be finished. I personally won't have time for a week or two. But it's an easy one if u know babel plugins. But if u don't, it's the perfect way to learn it. If u google james Kyle's babel handbook an excellent doc to learn it comes up. 

If you need it, is really try to take a look at the source and see if you can find what's missing.

**Comment by Aetherall** [comment]
Actually, the feature I really need Is to pass chunkName as prop ( for UniversalImport )

````javascript
import universal from 'react-universal-component'
const UniversalComponent = universal(props => import(`./${props.page}`))

<UniversalComponent page='Foo' chunkName='very-deep-foo' />

      ↓ ↓ ↓ ↓ ↓ ↓

import universal from 'react-universal-component'
import universalImport from 'babel-plugin-universal-import/universalImport.js'
import importCss from 'babel-plugin-universal-import/importCss.js'
import path from 'path'

const UniversalComponent = universal(props => universalImport({
  chunkName: props => props.chunkName || props.page, // simple OR that doesn't look simple anymore in a babel plugin
  path: props => path.join(__dirname, `./${props.page}`),
  resolve: props => require.resolveWeak(`./${props.page}`),
  load: props => Promise.all([
    import( /* webpackChunkName: '[request]' */ `./${props.page}`),
    importCss(page)                     //    <====            It shouldn't be props.page ?
  ]).then(proms => proms[0])
}));

<UniversalComponent page='Foo' chunkName='very-deep-foo' />
````

The fact is that I'm trying to use nested Universal Components but the resulting webpack chunk herits his name from his parent and looks like 'dashboard-posts' ( for 'posts' to resolve )

The absolute ultimate mindblowing behaviour would be for a Univesal Component to know on which UC it depends and to compose himself his UniversalImport chunkName

Honestly I really don't know anything about babel plugins so I will take a look into that doc and see if I can get to something

**Comment by faceyspacey** [comment]
a component's chunk name has nothing to do with a parent universal component. at least to the best of my knowledge. as mentioned in the other issue, it's likely based on your folder structure. if ur using dynamic expressions, its best to not have file in a folder for which u dont want to become code splitting entry points. 

if you're seeing hyphens in your chunk names its cuz webpack is recursively creating chunks for every file in every nested folder and so on. you likely don't webpack doing all that extra work. but webpack-flush-chunks is still able to find such files.

also you can pass `chunkName` or any prop you want to generate the chunk name within a dynamic expression. but keep in mind you have to generate the chunk name consistently. basically the `import()` is what generates the chunk name. so u cant do one thing for one and not the others. and if u skipped the babel plugin and did a custom thing just for the `chunkName` option it's not gonna match the `import()` within the `load` option. They have to match. It sounds like ur trying to hack it in a way that it just cant work for.

**Pull request closed without merging**
