### PR TITLE
Remove file property containing absolute path to file

### PR DESCRIPTION
**Pull request by Arturszott**
Solves: https://github.com/faceyspacey/babel-plugin-universal-import/issues/60

### CODE REVIEW

**Comment by ScriptedAlchemy** [comment]
@faceyspacey See anything wrong with this. AFIK it shouldnt cause an issue?

**Comment by Arturszott** [comment]
@faceyspacey @ScriptedAlchemy Can I do anything to speed up review of this PR?

**Comment by faceyspacey** [comment]
Make it relative please

**Comment by Arturszott** [comment]
@faceyspacey I found that https://github.com/babel-utils/babel-plugin-tester tells:
```
// only necessary if you use fixture or outputFixture in your tests
  filename: __filename,
```

In tests there is no use of fixtures, so what stop us from removing this at all?
This field is not listed in the documentation for the plugin.

**Comment by ScriptedAlchemy** [comment]
@faceyspacey ☝️ 

Perhaps, for developers to use within their application? 
If I'm correct, that object is accessible to coders. Needing a relative path might be useful?

Cannot confirm this though

**Comment by ScriptedAlchemy** [comment]
@Arturszott, could you make it relative and we will merge your update

**Pull request closed without merging**
