### PR TITLE
feat(loadOption): Nested chunknames as major release

### PR DESCRIPTION
**Pull request by ScriptedAlchemy**
Reverted this from 1.5.2 in order to re-introduce as a breaking change with a major release version bump. I also added more conventional looking tests

BREAKING CHANGE: Chunknames no longer output directories. If the chunkname was components/component,then the output would be a directory called components with the component inside it. Keeping with webpack 3 chunking conventions, chunk folders are represented in the filename with a hyphen as a seperator: components-component.js. the side affect is flattened build outputs

re #45

### CODE REVIEW

**Comment by ScriptedAlchemy** [comment]
Just double check you are happy with it :) 

I gave It a sanity check already

**Comment by faceyspacey** [comment]
ok, lets just hope that breaking change text makes commitizen work correctly--its been a long time since i've done a BC lol

**Comment by faceyspacey** [comment]
nicely done. it worked: https://www.npmjs.com/package/babel-plugin-universal-import

**Comment by ScriptedAlchemy** [comment]
Dude I love commitizen! Im looking at implementing it on all my projects.
Such a good idea, it really makes commits informative

**Pull request merged**
