### PR TITLE
Major release nested chunknames

### PR DESCRIPTION
**Pull request by ScriptedAlchemy**
Couldn't open a PR via commitizen because there was no diff against master, ill amend the commit right after the merge so that the reverted changes also show. Just opening it ahead of time so Its ready to go. please dont merge it this branch till I can check it after you merge PR 1

Ive merged the first pr I opened on my branch, then staged the removed changes back into this branch
I only reverted the nested chunknames commit, there was one file that fixed the importCSS bug where it used the chunkname not the file name. So that fix wont be reverted.

Hope it makes sense. Bottom line, I rolled back the breaking change, opened a revert PR, opened a new PR with the breaking change

Have a look at the diff on my branch

https://github.com/zackljackson/babel-plugin-universal-import/compare/master...zackljackson:major-release-nested-chunknames?expand=1

### CODE REVIEW

**Comment by faceyspacey** [comment]
Ready when you are. ...just make sure to specify the "breaking changes" field in commitizen, and that will automatically trigger a major version bump once merged to master.

**Comment by ScriptedAlchemy** [comment]
@faceyspacey 
Okay! Sure thing, just check the following commit (the last one)

Should be correct?
https://github.com/faceyspacey/babel-plugin-universal-import/pull/48/commits/7ef72afed68fc5c8810518088e5a696d55ddeae4

**Comment by faceyspacey** [comment]
Was there a reason you closed this? Your commit looks good re the breaking change.

**Comment by ScriptedAlchemy** [comment]
I’d run a script which rewrote some unintended directories git history. I did a hard reset off the upstream and opened another PR, in hindsight it was probably not necessary.

**Comment by faceyspacey** [comment]
I dont see another PR? What's wrong with this one? 

It correctly had the breaking change, so it just had to be merged.

**Comment by ScriptedAlchemy** [comment]
I was just being safe, i saw other commit messages in it (at least on my
side) and didnt want to screw up anything or risk merging a fishy branch.
The merged change was correct and everything looks on master. Again might
have been an unnecessary precaution

**Pull request closed without merging**
