### PR TITLE
fix: cleanup

### LINKED ISSUE #135: Cleaning
Here's a list of changes I would like to suggest to cleanup this package. It will be followed by a corresponding PR.

- [x] use strings to define `repository` and `bugs` urls in `package.json`
- [x] move `dependencies` and `peerDependencies` upward in `package.json`
- [x] replace `.npmignore` by `packages.files`
- [x] update `dependencies` and `devDependencies`
- [x] remove unneeded `devDependencies`
- [x] delete unneeded `.eslintignore`
- [x] remove non-existing paths/file in `.codeclimate.yml`
- [x] remove non-existing paths in `.gitignore`
- [x] cleanup `.eslintrc.js`
- [x] Improve `README.md`

All those changes have been tested by running `npm run lint`, `npm run test`, `npm pack`, and by installing the package in a test project. CI may require a specific attention on the update of the related packages.

***

<details><summary><strong>Use strings to define <code>repository</code> and <code>bugs</code> urls in <code>package.json</code></strong></summary>
<p>

This change makes use of strings to define `repository` and `bugs` urls instead of objects:</p>
> If you want to provide only a url, you can specify the value for “bugs” as a simple string instead of an object.

https://docs.npmjs.com/files/package.json#bugs

> For GitHub, GitHub gist, Bitbucket, or GitLab repositories you can use the same shortcut syntax you use for npm install

https://docs.npmjs.com/files/package.json#repository
</details>

<details>
<summary><strong>Move <code>dependencies</code> upward in <code>package.json</code></strong></summary>
<p>

When a user wants to check the `dependencies` to resolve an issue in its project, I believe it shouldn't have to look at the bottom of the `package.json`, and that it should found it before `devDependencies`, which only concern contributors.</p>
</details>

<details>
<summary><strong>Replace <code>.npmignore</code> by <code>packages.files</code></strong></summary> 
<p>

This change defines the packaged files using `files` instead of excluding files from the package using `.npmignore`. I believe the first strategy is more robust.</p>
</details>

<details><summary><strong>Update <code>dependencies</code> and <code>devDependencies</code></strong></summary>
<p>

- `@babel/core` from v7.9.0 to v7.11.4
- `@babel/helper-module-imports` from v7.0.0 to v7.10.4
- `@babel/plugin-transform-modules-commonjs` from v7.9.0 to v7.10.4.
- `babel-plugin-tester` from v5.5.2 to v9.2.0.
    - requires updating its import in `__tests__/index.test.js`
    - requires updating Jest snapshot (only code formating differences)
    - allows to remove `@babel/plugin-syntax-dynamic-import` since `babel-plugin-tester@latest` depends on `@babel/parser`, which supports the syntax of dynamic import since v7.8.0 (`dependency` of `@babel/core@v7.8.0`).
- `jest` from v21.2.1 to v26.4.2
    - requires updating snapshots (label formating differences)
    - allows to remove `babel-core` and `babel-jest`
- `eslint` from v6.8.0 to v7.7.0
    - requires removing `parserOptions.allowImportExportEverywhere` in `.eslintrc.js`
    - requires removing `ecmaFeatures.generators` and `ecmaFeatures.experimentalObjectRestSpread` in `.eslintrc.js`
    - allows to remove `babel-eslint`
- `eslint-config-airbnb` from v18.1.0 to v18.2.0
- `eslint-plugin-import` from v2.20.2 to v2.22.0
- `eslint-plugin-jsx-a11y` from v6.2.3 to v6.3.1
- `eslint-plugin-react` from v7.19.0 to 7.20.6
- `lint-staged` from v5.0.0 to v10.2.13
    - v9.0.0 removes advanced config options, which should now be passed inline via the CLI (eg. `--verbose`)
    - v10.0.0 has a breaking change that requires removing `git add` (executed implicitly)
- `prettier` from v1.19.1 to v2.1.1
- `semantic-release` from v6.3.6 to v17.1.1
    - requires replacing `semantic-release pre && npm publish && semantic-release post` by `semantic-release` (v9)
- `commitizen` from v4.0.4 to v4.2.1
- `cz-conventional-changelog` from v3.1.0 to v3.2.1
</p>
</details>

<details><summary><strong>Remove unneeded <code>devDependencies</code></strong></summary>
<p>

This change removes the following packages:</p>
- @babel/cli: not required nor used anywhere
- @babel/preset-react: not required since there's no React code
    - requires removing its usage in the `babelOptions` used to run tests
- babylon-options: not required since `@babel/core` (via `@babel/parser`, successor of `babylon`) parses dynamic import, which is at stage 4
    - requires removing its usage in the `babelOptions` used to run tests
- eslint-plugin-flowtype: not required since there's no declared flow types
- husky: not required nor used anywhere
- rimraf: not required nor used anywhere

Removing `eslint-plugin-flowtype` also implies removing:

- `--parser=flow` as a `prettier` arg in `package.json`
- `flow` related `plugins`, `extends`, `settings` and `rules` in `.eslintrc.js`
- `flow-typed` (non-existing path) in excluded paths defined in `.codeclimate.yml` and `.eslintignore`
</details>

<details>
<summary><strong>Delete <code>.eslintignore</code></strong></summary>
<p>

This change removes non-existing paths `dist` and `docs`, as well as `node_modules`:</p>
> In addition to any patterns in the .eslintignore file, ESLint always follows a couple implicit ignore rules even if the --no-ignore flag is passed. The implicit rules are as follows: node_modules/ is ignored. [...]

https://github.com/eslint/eslint/blob/4.x/docs/user-guide/configuring.md
</details>

<details><summary><strong>Remove non-existing paths in <code>.codeclimate.yml</code></strong></summary>
<p>

This change removes `importCss.js` (non-existing file) defined as `ratings.path`, and `docs/`, `dist/`, `.vscode/` (non-existing paths) as `exclude_paths`.</p>
</details>

<details><summary><strong>Remove non-existing paths in <code>.gitignore</code></strong></summary>
<p>

This change removes `dist` (doesn't exist), `yarn-error.log` (duplicate of `*.log`), and re-order rules alphabetically.</p>
</details>

<details><summary><strong>Clean up <code>.eslintrc.js</code></strong></summary>
<p>

This change removes `window|document|__DEV__|CONFIG|describe|it|beforeEach|fetch|alert` from `globals`, which are not used in this package, and sort rules alphabetically.</p>
</details>

<details><summary><strong>Improve <code>README.md</code></strong></summary>
<p>

- Add a concrete description of the package (citing the related Medium post)
- Simplify the examples (use the second one, but both are using "dynamic import", ie. import as a function)
- Re-order the plugin actions (wrapping with `universal` and inject chunk name as a Webpack magic comment)
- Remove the note on `extract-css-chunks-webpack-plugin`: there's no more relation w/ this plugin anymore since v3.0.0
- Remove the note on using this plugin with other tools, since it implies that they export a `universal` function, and PR #136 will make this note outdated anyway
- Add a link to the Medium post to get further doc on motivations/history of this plugin
- Simplify the description of the plugin options
- Re-order sections
- Fix formatting and typos
</details>

### PR DESCRIPTION
**Pull request by cdoublev**
Fix #135 (and other PR/issues).

### CODE REVIEW

**Comment by ScriptedAlchemy** [comment]
A much needed cleanup, thank you! 

Should this be a semver patch, fix, or major release based on all the changes in this PR?

Semver looks like it's mostly chores

**Comment by ScriptedAlchemy** [comment]
Also that issue description is immaculate, detailed and easy to digest. Rarely see that unless it's a bot 😂

**Comment by cdoublev** [comment]
Hmmm, I would say a minor update (patch < minor < major), since the only code changes (in `index.js`) were done by ESLint, but the single `dependency` of this package (`@babel/helper-module-imports`) has received a minor update. 

Maybe I have some OCDs when it comes to not messing up other people's work, true! Feel free to change amend whatever seems wrong to you.

**Comment by cdoublev** [comment]
Actually, you upgraded ESLint from v4.19.0 to v6.8.0, but you didn't run it to fix issues. Running it would also have resulted in transformation of `Object.assign()` and dot prop accessor to object spread/destructuring. Then I upgraded it to v7.7.0 in this PR. I'm not sure if it matters, since there's no `engine.node` defined in `package.json`, but to be strict with semver, then this should be a minor update, ie. `vi.i+.i`.

**Pull request closed without merging**
