### PR TITLE
 feat(universal-loader): Webpack 4 Support

### LINKED ISSUE #30: async loaded stylesheets not editable in Chrome
Hey guys,

I am not really sure where to put this, but before I file an issue for Chromium I wanted to check with you first:

When a stylesheets gets injected async into my html then the styles get applied but are not editable in the Chrome dev tools. Whenever I change the link element that contains the stylesheet, thus enforcing Chrome to reload the resource, the styles become editable.

After a stylesheet got injected (greyed out areas in inspector are not editable)
screen shot 2017-12-08 at 06 56 12

After Chrome has reloaded the stylesheet
screen shot 2017-12-08 at 06 56 48

Is this at all something that belongs to this babel module?

### PR DESCRIPTION
**Pull request by ScriptedAlchemy**
The new css chunks plugin manages and loads css on its own. babel no longer needs to worry about it.
Update is to support universal webpack 4 updates as a whole

BREAKING CHANGE: Webpack 4 & extract-css-chunks 3 is required

fix #30, #35,  re #29

### CODE REVIEW

**Review by faceyspacey — COMMENTED** [review]
looks excellent to me. good job on removing extract css chunk's dep on this. ..the readme looks like u might wanna add some more of ur own fresh words and take on things.

**Comment by ScriptedAlchemy** [comment]
Yeah ill add more writing around it for sure. Ill need to think on it and can issue an update in the next few days

**Comment by ScriptedAlchemy** [comment]
All clear to merge? On both my PRs?

**Comment by faceyspacey** [comment]
all clear

**Comment by ScriptedAlchemy** [comment]
Fantastic --  tomorrow morning it is!

**Pull request merged**
