### PR TITLE
feat: Removing babel chunkname renaming

### PR DESCRIPTION
**Pull request by ScriptedAlchemy**
This plugin will no longer rename chunks to replace slashes with dashes

BREAKING CHANGE: The plugin will no longer rename chunks to dashes

### CODE REVIEW

**Comment by konpikwastaken** [comment]
Really wanted to do this, huh :). 

I saw you removed rename for nested chunks as well - did you give dynamic imports inside dynamic imported chunks a test?

**Comment by ScriptedAlchemy** [comment]
So this should work fine with nested imports. It would just create more folders. 

Only issue is if you try to use Universal as a string. Because folder chunks (importing a folder with a variable) causes chunknames to include folder-chunk. 

What I’ll do shortly is try and update flush chunks so it attempts to locate both slashed and dashed chunks. 

That’s where the real issue is. The client is fully managed by webpack. 

As I work with webpack more and more, I’m looking at solutions to consolidate chunk resolution into the build itself, just for servers.

**Comment by rtymchyk** [comment]
@ScriptedAlchemy it doesn't look like flush chunks has that behaviour and the only option is to indicate a config `ignoreBabelRename` with every `universal` call. Is there a better solution?

**Comment by oskarleonard** [comment]
@ScriptedAlchemy  Why is this change needed? Isnt a flatten structure better? https://github.com/faceyspacey/babel-plugin-universal-import/issues/45

This is how i use universal: 
```
const options = {
  error: ErrorLoadingRouteChunk,
  loading: Loader,
};

universal(import('pages/homePage/HomePage'), options)
```

With babel-plugin-universal-import v3 it produces a chunk with dashes `pages-homePage-HomePage.js` but with v4 it now becomes a folder structure `pages/homePage/HomePage.js`. 

Is it better to have a folder structure than dashes?

(i am using react-universal-component v4)

**Pull request merged**
