### PR TITLE
Add disableWarnings option

### PR DESCRIPTION
**Pull request by okcoker**
Addresses #21 and #23.

### CODE REVIEW

**Comment by faceyspacey** [comment]
awesome. thanks.

why not pass the option directly through the template here:

https://github.com/okcoker/babel-plugin-universal-import/blob/afb100920a1af8116eb773e93d370b027496fd7c/index.js#L130

**Comment by okcoker** [comment]
I actually did that at first, but I thought I'd save the couple bytes and extra diffs within the snapshots.

**Comment by okcoker** [comment]
and by save a couple bytes, I mean not turning `importCss('./Foo')` into `importCss('./Foo', {})` when `disableWarnings` is not provided.

**Comment by faceyspacey** [comment]
feel you. still probably most idiomatic just to pass a 4th key/val to the template.

**Comment by okcoker** [comment]
I can update it.

**Comment by okcoker** [comment]
Ok updated. I basically cmd + z'd a few times. Originally I had it like the latest push so you could easily add additional options in the future but then I thought that might be too forward so I had undid that.

Let me know if this works.

**Comment by faceyspacey** [comment]
Very nice. Would be nice if the options not just for CSS (if we were ever to have any) were handled by this, but I like having this in the code for future reference. I like how you made it its own function.

**Comment by okcoker** [comment]
Oh yea that was another reason I got rid of `cssOptions` in the first place because `disableWarnings` could potentially apply to non css-y things in the future as well. 

Ah well. Thanks for the quick merge!

**Comment by faceyspacey** [comment]
just one thing for future reference; use `npm run cm` to make commits. it formats them a special way that will automatically deploy to NPM from travis when merged to master.

**Pull request merged**
