### PR TITLE
🐛 FIX: Require module

### PR DESCRIPTION
**Pull request by luangjokaj**
This fixed the previous release and issue #113.

@ScriptedAlchemy I believe this is a typo from the previous release, I pushed a fix. Can we merge this?

### CODE REVIEW

**Review by ScriptedAlchemy — APPROVED** [review]

**Comment by luangjokaj** [comment]
@ScriptedAlchemy can you publish a release on npm? 😄

**Comment by pablopalacios** [comment]
@luangjokaj what is the difference between module.require and require? My application doesn't work with this patch. It complains that react-universal-component module doesn't exist. However, if I rollback to 4.0.1, it works fine.

**Comment by ScriptedAlchemy** [comment]
Ci seems to be down on many of these projects now. I'll manually deploy

**Comment by pablopalacios** [comment]
@ScriptedAlchemy oh, I'm not sure if I got you but this is already released, no worries. I was updating my company app dependencies and react-universal-component stopped working because of this patch. It looks like SSR doesn't work with it if one doesn't use webpack at runtime. I did a small experiment and updated the babel plugin from this:

```javascript
var nodeRequire = typeof __non_webpack_require__ === 'undefined' ? module.require : __non_webpack_require__
universal = nodeRequire('react-universal-component')
```

To this:

```javascript
if (typeof __non_webpack_require__ === 'undefined') {
  universal = require('react-universal-component')
} else {
  universal = __non_webpack_require__('react-universal-component')
}
```
And then everything works again (SSR is working and no warning is logged). So this is why I came here to ask about the difference between `require` and `module.require`.

**Comment by ScriptedAlchemy** [comment]
Open pr if need

**Pull request merged**
